[build]

  publish = "dist/portfolio-victoriya/browser"
command = "ng build --prod"

[[plugins]]
  package = "@netlify/angular-runtime"
  
  [[redirects]]
from = "/*"
to = "/index.html"
status = 200 